### PR TITLE
Update example to OCaml 4.13

### PR DESCRIPTION
**Pull request by MisterDA**

### CODE REVIEW

**Comment by smorimoto** [comment]
Thank you! Could you update the example as well?!

**Comment by MisterDA** [comment]
Done, I ran `sed 's/4\.12/4.13/g' -i README.md examples.md`.

**Review by smorimoto — APPROVED** [review]

**Comment by smorimoto** [comment]
Thank you!

**Comment by MisterDA** [comment]
Well now that 4.13.1 is just around the corner, it seems that we'll have a follow-up PR.

**Pull request merged**
