### PR TITLE
Add a security policy

### PR DESCRIPTION
**Pull request by smorimoto**
This is very draft of draft, and I'm looking for better content!

### CODE REVIEW

**Comment by smorimoto** [comment]
@dra27 Do you have any ideas?

**Comment by dra27** [comment]
It's a good idea, thank you! OCaml core maintainers sounds a bit like the compiler core development team, which isn't the same thing. Regardless, there should be a contact mechanism.

However, the easiest may just be to turn on the new [private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) feature and then refer to that here?

The policy is then:
- Please report potential security vulnerabilities using [the advisories](https://github.com/ocaml/setup-ocaml/security/advisories) tool
- The advisory will be reviewed by the maintainers of this repo (_perhaps it would be prudent to have these visible - I don't think we are specifically visible at the moment?)
- The advisory will be made public when patches to the two major tags (`@v1` and `@v2`) have been released

?

**Comment by smorimoto** [comment]
I don't have full administrator rights in the repository, so I may need to ask Anil (or you?) for it.

**Comment by dra27** [comment]
It's @avsm, yes

**Comment by avsm** [comment]
It's now activated for this repository (with plenty of opinions: https://github.com/ocaml/setup-ocaml/security/code-scanning)

**Comment by smorimoto** [comment]
@dra27 I just updated it

**Pull request merged**
