### PR TITLE
Remove usage of opam depext plugin

### PR DESCRIPTION
**Pull request by tmattio**
`setup-ocaml` seems to be using opam.2.1.0 now, so installing `opam-depext` fails with a constraint error.

https://github.com/ocaml/v3.ocaml.org-server/runs/3202898179

```
 [ERROR] opam-depext unmet availability conditions, e.g. 'opam-version >= "2.0.0~beta5" & opam-version < "2.1"'
  '/Users/runner/hostedtoolcache/opam/2.1.0/x86_64/opam install opam-depext' failed.
```

This PR removes the `depext` plugin installation. I am testing the patch in https://github.com/ocaml/v3.ocaml.org-server/pull/69, but for some reason, `opam install` does not install the depext itself, even with `OPAMYES=1` and the `-y` argument.

```
Run opam install --deps-only --with-test -y .
...
<><> Handling external dependencies <><><><><><><><><><><><><><><><><><><><><><>
Let opam run your package manager to install the required system packages?
(answer 'n' for other options) [Y/n] n
This command should get the requirements installed:

    apt-get install libev-dev

You can retry with '--assume-depexts' to skip this check, or run 'opam option depext=false' to permanently disable handling of system packages altogether.
```

I'm not sure if this should be an issue on opam?

### CODE REVIEW

**Review by smorimoto — CHANGES_REQUESTED** [review]
This part of the README input list should also be removed.

**Comment by smorimoto** [comment]
Oops, GitHub's code selection review seems to be invalid outside of the "actual" diff locations...

**Comment by AltGr** [comment]
You need `OPAMCONFIRMLEVEL=unsafe-yes`. We don't want to run system commands with `sudo` even for users who run with `-y` :)

**Comment by smorimoto** [comment]
The remaining (or newly born) problem here is that Windows is not yet updated to opam 2.1, but I believe it should be updated soon, so I think we can merge this and then create a new release.

**Review by smorimoto — APPROVED** [review]

**Comment by smorimoto** [comment]
Thanks @tmattio!

**Comment by dra27** [comment]
Note that opam 2.1.0 doesn't have native depext support for Windows, so if opam-repository-mingw is updated with it (I don't know if that's happening, given the deprecation) then the Windows runners still need `depext-cygwinports` to be installed... so Windows will remain slightly different regardless.

**Comment by smorimoto** [comment]
Then, we still need additional support for Windows. Well, it would seem enough to install packages that are only needed for depext on Windows.

**Pull request merged**
