### PR TITLE
uses opam-disable-sandboxing for opam cache key computation

### LINKED ISSUE #635: opam-disable-sandboxing variable is ignored by the cache system
A common use case is to run the workflow, discover that tests fail due to the sandboxing, and disable it using the `opam-disable-sandboxing` variable. However, since this variable is not taken into account when the cache key is computed, nothing will happen (i.e., the opam will not be initialized) and the failures will continue. It took me a few hours to figure out that the failures are still due 
 to the opam cache, which I have disabled :) 

Workarounds involved adding a cache prefix or deleting the caches. But for a better user experience, the change in this variable shall be reflected in the cache key.

### PR DESCRIPTION
**Pull request by ivg**
Resolves #635.

### CODE REVIEW

**Comment by ivg** [comment]
I don't have the development setup, so I can't generate index.js, but I hope you can take it from here :)

**Comment by smorimoto** [comment]
OK. But just needs a CHANGELOG entry.

**Review by smorimoto — APPROVED** [review]

**Comment by ivg** [comment]
Done!

**Comment by smorimoto** [comment]
Thank you so much! @ivg

**Pull request merged**
