### PR TITLE
Add the bin directory under the local switch to the system path

### LINKED ISSUE #70: Option to add binaries to path
It would be nice if I could set some variable to `true` to have the opam environment added to path, so I don't need to `opam exec` everything.  (It might be the case that running `opam env >> $GITHUB_ENV` is enough?)

### PR DESCRIPTION
**Pull request by smorimoto**
Closes #70

### CODE REVIEW

**Comment by smorimoto** [comment]
I believe the path to add is enough (`<CWD>/_opam/bin`), but is there anything I missed?

**Comment by dra27** [comment]
It's a nice simple idea, but this doesn't work, I'm afraid (it will be brittle):
- Some time in the next few months, msvc will start adding other directories to `PATH` (so compiler in `PATH` won't work)
- The other environment variables set by `opam exec` matter - for example, `CAML_LD_LIBRARY_PATH` in opam-repository's current setup _could_ cause problems 

I think it's important if the action exports the environment that it exports the _same_ one as `opam exec` would give. There are a few solutions which could work:
- Pick a shell (for example `opam env --shell=bash`) and parse the output. The annoying thing here is that you have to find the _existing_ value of environment variables to work out the change. For example, on my system:
```bash
dra@thor:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/dra/.dotnet/tools
dra@thor:~$ opam env --shell=bash | grep ^PATH
PATH='/home/dra/.opam/dev-4.11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/dra/.dotnet/tools'; export PATH;
```
So you have to post-process the `PATH=` line to work out that it's really `PATH="/home/dra/.opam/dev-4.11/bin:/usr/local/sbin:$PATH"` (and remember that switches can _append_ items to variables as well).
- Parse `_opam/.opam-switch/environment`. This is probably the best solution right now, though it's tedious to have to parse the file
- Update `opam` to support JSON export of the `environment` updates.

**Comment by smorimoto** [comment]
Indeed - and I think there is a cleaner solution with opam 2.2, so I'm closing this for now.

**Comment by dra27** [comment]
What's in opam 2.2 to help with this?

**Pull request closed without merging**
