### PR TITLE
Do not attempt to re-add the repository if it is not necessary

### PR DESCRIPTION
**Pull request by smorimoto**
This has a fairly big effect in environments that have poor I/O POWER...

### CODE REVIEW

**Comment by dra27** [comment]
Looking at the logs, this doesn't appear to be working - all the tests are still running, e.g. `/Users/runner/hostedtoolcache/opam/2.0.8/x86_64/opam init default https://github.com/ocaml/opam-repository.git --auto-setup --bare --enable-shell-hook`?

**Comment by dra27** [comment]
Ah, I see now. I don't understand why you're hard-coding it to the default repository? `opam init` doesn't let you specify multiple repositories, so if the user is initialising one repository (_any_ repository) then you can do that at `opam init` and then not do any `opam repo add` commands. For example, if I initialised opam with _just_ the multicore repository, I think what you have you here would do:

```
opam init --auto-setup default https://github.com/ocaml/opam-repository.git --bare ...
opam repo remove default --all-switches
opam repo add multicore ...
```
when it could just have done:
```
opam init --auto-setup multicore https://github.com/ocaml-multicore/multicore-opam.git --bare ...
```
?

Similarly, for the case of two repositories (e.g. the default + multicore tests in the workflow), it's doing `opam init` with the standard default (that will be http), removing that and then adding the two. Why not just do `opam init` with the _last_ repository and then `opam add` the others (in reverse order - `opam repo add` adds the repository at the _highest_ priority, so it's like consing a list)? So for:

```
opam-repositories:
  multicore: https://github.com/ocaml-multicore/multicore-opam.git
  default: https://github.com/ocaml/opam-repository.git
```
do:
```
opam init --auto-setup default https://github.com/ocaml/opam-repository.git --bare --enable-shell-hook
opam repository add multicore https://github.com/ocaml-multicore/multicore-opam.git --all-switches --set-default
```

**Comment by dra27** [comment]
Incidentally, the multiple repositories feature appears to be adding the repositories the wrong way around (shouldn't multicore be the highest priority?)

```
> Run opam repo
[NOTE] These are the repositories in use by the current switch. Use '--all' to see all configured repositories.

<><> Repository configuration for switch /home/runner/work/setup-ocaml/setup-ocaml 
 1 default   git+https://github.com/ocaml/opam-repository.git
 2 multicore git+https://github.com/ocaml-multicore/multicore-opam.git
```

**Comment by smorimoto** [comment]
I think we need to clarify a few points.

> I don't understand why you're hard-coding it to the default repository?

The repositories that were configured for each platform (from v1) are indeed hard-coded, but they are only used if the user does not overwrite the repositories.

> `opam init` doesn't let you specify multiple repositories, so if the user is initialising one repository (_any_ repository) then you can do that at `opam init` and then not do any `opam repo add` commands. For example, if I initialised opam with _just_ the multicore repository, I think what you have you here would do:

Yes, your point is correct at first glance, but since we cache and carry the opam switch, I think we need to reset the state by removing all repositories that have already been added.

**Comment by smorimoto** [comment]
> Incidentally, the multiple repositories feature appears to be adding the repositories the wrong way around (shouldn't multicore be the highest priority?)

Oh! That's right, I just forgot to “reverse” things!

**Comment by dra27** [comment]
Resetting the repository state on each call is expensive (especially on Windows) - why not include the `opam-repositories` setting (or a hash of it) in the cache key? The number of times the workflow will run ≫ the number of times the user is likely to change the `opam-repositories` input.

**Comment by smorimoto** [comment]
Hmm, certainly...! I would like to try to figure out a better approach! It may change direction a little, so I will close this for now.

**Pull request closed without merging**
