### PR TITLE
Temporary workaround curl failure in Cygwin

### PR DESCRIPTION
**Pull request by dra27**
cf. https://cygwin.com/pipermail/cygwin/2023-December/255026.html, with thanks to @MSoegtropIMC for the diagnosis.

This will hopefully be fixed quickly upstream, but in the meantime.

### CODE REVIEW

**Comment by dra27** [comment]
This first push is to force the failure to show itself.

**Comment by dra27** [comment]
- https://github.com/ocaml/setup-ocaml/actions/runs/7265294067/job/19794696820?pr=742#step:3:114 shows the failure
- https://github.com/ocaml/setup-ocaml/actions/runs/7265365140/job/19794917304?pr=742#step:3:115 shows the fix working
- The current push of the PR is what needs merging - there's no need to bump any of the caches

**Comment by dra27** [comment]
The package has been rolled back (see https://cygwin.com/pipermail/cygwin/2023-December/255032.html) so we should be fine without this is.

**Comment by MSoegtropIMC** [comment]
@dra27: I wonder what is the best way to inform you properly about such issues next time - I usually find out first cause of the Coq Platform CI (which sets up a fresh cygwin once a day). The ocaml forum doesn't work for me for some reason (doesn't load after login). Should I just create an issue in setup-ocaml?

I guess posting in the cygwin forum with "opam" in the subject also did the job ...

**Comment by dra27** [comment]
An issue here on setup-ocaml is definitely helpful, but I realise that you're not actually using setup-ocaml in this context.

I used to have a better watch on the Cygwin list for opam and ocaml as keywords, which I forgot about when I migrated work email to gmail... your post to the Cygwin list reminds me to restore it!

To be honest, the whole process worked pretty well for me - I was alerted early-afternoon on 19th that there seemed to be a problem; I couldn't get to it straight away, but it took a very small amount of time to confirm that it was indeed curl that was the problem and it was not long before I checked for messages on the Cygwin list and saw yours. Had I had my own alert for that set-up, it would have shaved a few hours off, but that's solely my fault 🙂

**Pull request closed without merging**
