### PR TITLE
correct "ocaml-repositories" to "opam-repositories" in docs

### PR DESCRIPTION
**Pull request by TyOverby**
```diff
-      ocaml-repositories: |
+      opam-repositories: |
         default: https://github.com/fdopen/opam-repository-mingw.git#opam2
```

### CODE REVIEW

**Comment by smorimoto** [comment]
Looks good, but it's meant to be opam, not opal, right?

**Review by smorimoto — APPROVED** [review]

**Comment by TyOverby** [comment]
hahaha, oops!  Amazing that I managed to mis-spell it in a new way in my pull-request title :|

**Comment by smorimoto** [comment]
Nooo, not just the title, but the commit message! 😸

**Comment by TyOverby** [comment]
Oh, that's because I submitted this pull-request from the github website on my phone, so it re-used the title for the commit message...  Sadly it doesn't look like there's a way to edit the commit message from the website

**Comment by smorimoto** [comment]
I just fixed the commit message!

**Comment by smorimoto** [comment]
Thanks @TyOverby!

**Comment by TyOverby** [comment]
I just got to my computer and was about to pull this up to do the fix, only to find that you beat me to it! 
Thanks for the assistance, and thanks for the work that you do on setup-ocaml; my experience with it has been great so far!

**Pull request merged**
